baseURL = 'https://vamsikiran277.github.io/'
languageCode = 'en-us'
title = 'Vamsi Kiran | Firmware Engineer'
theme = 'PaperMod'

[outputs]
    home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
    unsafe = true

[params]
    env = "production"
    title = "Vamsi Kiran"
    description = "Firmware Engineer & Embedded Systems Architect specializing in CAN Protocol stacks, FreeRTOS, and low-level Linux drivers."
    author = "Vamsi Kiran"
    
    # Theme Logic
    defaultTheme = "dark"
    disableThemeToggle = true 
    
    # UI Features
    ShowReadingTime = true
    ShowShareButtons = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    
    assets = { disableFingerprinting = false }
    # Branding
    label = { text = "Home" }

    [params.profileMode]
        enabled = true
        title = "Vamsi Kiran Mekala"
        subtitle = "Embedded Systems Engineer with expertise in C/C++, Linux kernel/user space programming, and low-level driver development. Proven track record in designing communication protocol stacks (CAN) and optimizing hardware-software interfaces."
        
        imageUrl = "" 
        imageWidth = 0
        imageHeight = 0
        [[params.profileMode.buttons]]
            name = "View Projects"
            url = "/projects/"
        [[params.profileMode.buttons]]
            name = "View GitHub"
            url = "https://github.com/VamsiKiran277"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/VamsiKiran277"
    [[params.socialIcons]]
        name = "email"
        url = "mailto:vamsikiran167@gmail.com"
        title = "Gmail"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/vamsi-kiran-mekala-57135424a/"

[[menu.main]]
    name = "Resume"
    url = "resume"
    weight = 5
[[menu.main]]
    name = "Projects"
    url = "projects"
    weight = 10
[[menu.main]]
    name = "Search"
    url = "search"
    weight = 20
[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 30