baseURL = 'https://vamsikiran277.github.io/'
languageCode = 'en-us'
title = 'Vamsi Kiran | Firmware Engineer'
theme = 'PaperMod'

[params]
defaultTheme = "dark"

[params.profileMode]
enabled = true
title = "Hi, I'm Vamsi "
subtitle = "Aspiring Firmware & Embedded Systems Engineer  | IoT, RTOS, & Bare-Metal C"
imageUrl = "/images/profile.png" # We will add this image next!
imageWidth = 120
imageHeight = 150

[[params.profileMode.buttons]]
name = "View Projects"
url = "/projects/"

[[params.profileMode.buttons]]
name = "View GitHub"
url = "https://github.com/VamsiKiran277"

[[params.socialIcons]]
name = "github"
url = "https://github.com/VamsiKiran277"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/vamsi-kiran-mekala-57135424a/"